// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.coalvalue.rpc.grpc;

public interface FeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Feature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.grpc.Point location = 2;</code>
   */
  boolean hasLocation();
  /**
   * <code>.grpc.Point location = 2;</code>
   */
  com.coalvalue.rpc.grpc.Point getLocation();
  /**
   * <code>.grpc.Point location = 2;</code>
   */
  com.coalvalue.rpc.grpc.PointOrBuilder getLocationOrBuilder();
}
