// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.coalvalue.rpc.grpc;

public interface NotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Notification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientName = 1;</code>
   */
  java.lang.String getClientName();
  /**
   * <code>string clientName = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <code>string serverName = 2;</code>
   */
  java.lang.String getServerName();
  /**
   * <code>string serverName = 2;</code>
   */
  com.google.protobuf.ByteString
      getServerNameBytes();

  /**
   * <code>.grpc.topicType type = 3;</code>
   */
  int getTypeValue();
  /**
   * <code>.grpc.topicType type = 3;</code>
   */
  com.coalvalue.rpc.grpc.topicType getType();

  /**
   * <code>.grpc.Alert a = 6;</code>
   */
  boolean hasA();
  /**
   * <code>.grpc.Alert a = 6;</code>
   */
  com.coalvalue.rpc.grpc.Alert getA();
  /**
   * <code>.grpc.Alert a = 6;</code>
   */
  com.coalvalue.rpc.grpc.AlertOrBuilder getAOrBuilder();

  /**
   * <code>.grpc.Mode m = 4;</code>
   */
  boolean hasM();
  /**
   * <code>.grpc.Mode m = 4;</code>
   */
  com.coalvalue.rpc.grpc.Mode getM();
  /**
   * <code>.grpc.Mode m = 4;</code>
   */
  com.coalvalue.rpc.grpc.ModeOrBuilder getMOrBuilder();

  /**
   * <code>.grpc.Temp t = 5;</code>
   */
  boolean hasT();
  /**
   * <code>.grpc.Temp t = 5;</code>
   */
  com.coalvalue.rpc.grpc.Temp getT();
  /**
   * <code>.grpc.Temp t = 5;</code>
   */
  com.coalvalue.rpc.grpc.TempOrBuilder getTOrBuilder();
}
