// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.coalvalue.rpc.grpc;

public interface RouteNoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.RouteNote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.Point location = 1;</code>
   */
  boolean hasLocation();
  /**
   * <code>.grpc.Point location = 1;</code>
   */
  com.coalvalue.rpc.grpc.Point getLocation();
  /**
   * <code>.grpc.Point location = 1;</code>
   */
  com.coalvalue.rpc.grpc.PointOrBuilder getLocationOrBuilder();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
