// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.coalvalue.rpc.grpc;

public interface TempOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Temp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * set the temp 
   * </pre>
   *
   * <code>uint32 newTemp = 1;</code>
   */
  int getNewTemp();
}
