FROM jsurf/rpi-java
VOLUME /tmp
ADD carparking-0.0.1-SNAPSHOT.jar  /app.jar
ENV JAVA_OPTS=""
ENTRYPOINT java $JAVA_OPTS -Djava.library.path="/library" -Djava.security.egd=file:/dev/./urandom -jar /app.jar
