// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pushnotif.proto

package com.coalvalue.rpc.grpc.notif;

public interface AlertOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Alert)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Alerts could be.. check for open doors, temp dropping down too quickly 
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <pre>
   * Alerts could be.. check for open doors, temp dropping down too quickly 
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
