// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pushnotif.proto

package com.coalvalue.rpc.grpc.notif;

public interface ModeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Mode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * "heat" or "cold" 
   * </pre>
   *
   * <code>string newMode = 1;</code>
   */
  String getNewMode();
  /**
   * <pre>
   * "heat" or "cold" 
   * </pre>
   *
   * <code>string newMode = 1;</code>
   */
  com.google.protobuf.ByteString
      getNewModeBytes();
}
