// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pushnotif.proto

package com.coalvalue.rpc.grpc.notif;

public interface NotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Notification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientName = 1;</code>
   */
  String getClientName();
  /**
   * <code>string clientName = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <code>string serverName = 2;</code>
   */
  String getServerName();
  /**
   * <code>string serverName = 2;</code>
   */
  com.google.protobuf.ByteString
      getServerNameBytes();

  /**
   * <code>.grpc.topicType type = 3;</code>
   */
  int getTypeValue();
  /**
   * <code>.grpc.topicType type = 3;</code>
   */
  topicType getType();

  /**
   * <code>.grpc.Alert a = 6;</code>
   */
  boolean hasA();
  /**
   * <code>.grpc.Alert a = 6;</code>
   */
  Alert getA();
  /**
   * <code>.grpc.Alert a = 6;</code>
   */
  AlertOrBuilder getAOrBuilder();

  /**
   * <code>.grpc.Mode m = 4;</code>
   */
  boolean hasM();
  /**
   * <code>.grpc.Mode m = 4;</code>
   */
  Mode getM();
  /**
   * <code>.grpc.Mode m = 4;</code>
   */
  ModeOrBuilder getMOrBuilder();

  /**
   * <code>.grpc.Temp t = 5;</code>
   */
  boolean hasT();
  /**
   * <code>.grpc.Temp t = 5;</code>
   */
  Temp getT();
  /**
   * <code>.grpc.Temp t = 5;</code>
   */
  TempOrBuilder getTOrBuilder();
}
