// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pushnotif.proto

package com.coalvalue.rpc.grpc.notif;

/**
 * Protobuf type {@code grpc.Notification}
 */
public  final class Notification extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.Notification)
    NotificationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Notification.newBuilder() to construct.
  private Notification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Notification() {
    clientName_ = "";
    serverName_ = "";
    type_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Notification(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            clientName_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            serverName_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 34: {
            Mode.Builder subBuilder = null;
            if (m_ != null) {
              subBuilder = m_.toBuilder();
            }
            m_ = input.readMessage(Mode.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(m_);
              m_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            Temp.Builder subBuilder = null;
            if (t_ != null) {
              subBuilder = t_.toBuilder();
            }
            t_ = input.readMessage(Temp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(t_);
              t_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            Alert.Builder subBuilder = null;
            if (a_ != null) {
              subBuilder = a_.toBuilder();
            }
            a_ = input.readMessage(Alert.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(a_);
              a_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Pushnotif.internal_static_grpc_Notification_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Pushnotif.internal_static_grpc_Notification_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Notification.class, Builder.class);
  }

  public static final int CLIENTNAME_FIELD_NUMBER = 1;
  private volatile Object clientName_;
  /**
   * <code>string clientName = 1;</code>
   */
  public String getClientName() {
    Object ref = clientName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      clientName_ = s;
      return s;
    }
  }
  /**
   * <code>string clientName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getClientNameBytes() {
    Object ref = clientName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      clientName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVERNAME_FIELD_NUMBER = 2;
  private volatile Object serverName_;
  /**
   * <code>string serverName = 2;</code>
   */
  public String getServerName() {
    Object ref = serverName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      serverName_ = s;
      return s;
    }
  }
  /**
   * <code>string serverName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getServerNameBytes() {
    Object ref = serverName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      serverName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private int type_;
  /**
   * <code>.grpc.topicType type = 3;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.grpc.topicType type = 3;</code>
   */
  public topicType getType() {
    topicType result = topicType.valueOf(type_);
    return result == null ? topicType.UNRECOGNIZED : result;
  }

  public static final int A_FIELD_NUMBER = 6;
  private Alert a_;
  /**
   * <code>.grpc.Alert a = 6;</code>
   */
  public boolean hasA() {
    return a_ != null;
  }
  /**
   * <code>.grpc.Alert a = 6;</code>
   */
  public Alert getA() {
    return a_ == null ? Alert.getDefaultInstance() : a_;
  }
  /**
   * <code>.grpc.Alert a = 6;</code>
   */
  public com.coalvalue.rpc.grpc.notif.AlertOrBuilder getAOrBuilder() {
    return getA();
  }

  public static final int M_FIELD_NUMBER = 4;
  private Mode m_;
  /**
   * <code>.grpc.Mode m = 4;</code>
   */
  public boolean hasM() {
    return m_ != null;
  }
  /**
   * <code>.grpc.Mode m = 4;</code>
   */
  public Mode getM() {
    return m_ == null ? Mode.getDefaultInstance() : m_;
  }
  /**
   * <code>.grpc.Mode m = 4;</code>
   */
  public com.coalvalue.rpc.grpc.notif.ModeOrBuilder getMOrBuilder() {
    return getM();
  }

  public static final int T_FIELD_NUMBER = 5;
  private Temp t_;
  /**
   * <code>.grpc.Temp t = 5;</code>
   */
  public boolean hasT() {
    return t_ != null;
  }
  /**
   * <code>.grpc.Temp t = 5;</code>
   */
  public Temp getT() {
    return t_ == null ? Temp.getDefaultInstance() : t_;
  }
  /**
   * <code>.grpc.Temp t = 5;</code>
   */
  public com.coalvalue.rpc.grpc.notif.TempOrBuilder getTOrBuilder() {
    return getT();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClientNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientName_);
    }
    if (!getServerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serverName_);
    }
    if (type_ != topicType.ALERT.getNumber()) {
      output.writeEnum(3, type_);
    }
    if (m_ != null) {
      output.writeMessage(4, getM());
    }
    if (t_ != null) {
      output.writeMessage(5, getT());
    }
    if (a_ != null) {
      output.writeMessage(6, getA());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClientNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientName_);
    }
    if (!getServerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serverName_);
    }
    if (type_ != topicType.ALERT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, type_);
    }
    if (m_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getM());
    }
    if (t_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getT());
    }
    if (a_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getA());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Notification)) {
      return super.equals(obj);
    }
    Notification other = (Notification) obj;

    boolean result = true;
    result = result && getClientName()
        .equals(other.getClientName());
    result = result && getServerName()
        .equals(other.getServerName());
    result = result && type_ == other.type_;
    result = result && (hasA() == other.hasA());
    if (hasA()) {
      result = result && getA()
          .equals(other.getA());
    }
    result = result && (hasM() == other.hasM());
    if (hasM()) {
      result = result && getM()
          .equals(other.getM());
    }
    result = result && (hasT() == other.hasT());
    if (hasT()) {
      result = result && getT()
          .equals(other.getT());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getClientName().hashCode();
    hash = (37 * hash) + SERVERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getServerName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (hasA()) {
      hash = (37 * hash) + A_FIELD_NUMBER;
      hash = (53 * hash) + getA().hashCode();
    }
    if (hasM()) {
      hash = (37 * hash) + M_FIELD_NUMBER;
      hash = (53 * hash) + getM().hashCode();
    }
    if (hasT()) {
      hash = (37 * hash) + T_FIELD_NUMBER;
      hash = (53 * hash) + getT().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Notification parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Notification parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Notification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Notification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Notification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Notification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Notification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Notification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Notification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Notification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Notification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Notification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Notification prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.Notification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.Notification)
      com.coalvalue.rpc.grpc.notif.NotificationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Pushnotif.internal_static_grpc_Notification_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Pushnotif.internal_static_grpc_Notification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Notification.class, Builder.class);
    }

    // Construct using com.coalvalue.rpc.grpc.notif.Notification.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      clientName_ = "";

      serverName_ = "";

      type_ = 0;

      if (aBuilder_ == null) {
        a_ = null;
      } else {
        a_ = null;
        aBuilder_ = null;
      }
      if (mBuilder_ == null) {
        m_ = null;
      } else {
        m_ = null;
        mBuilder_ = null;
      }
      if (tBuilder_ == null) {
        t_ = null;
      } else {
        t_ = null;
        tBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Pushnotif.internal_static_grpc_Notification_descriptor;
    }

    public Notification getDefaultInstanceForType() {
      return Notification.getDefaultInstance();
    }

    public Notification build() {
      Notification result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public Notification buildPartial() {
      Notification result = new Notification(this);
      result.clientName_ = clientName_;
      result.serverName_ = serverName_;
      result.type_ = type_;
      if (aBuilder_ == null) {
        result.a_ = a_;
      } else {
        result.a_ = aBuilder_.build();
      }
      if (mBuilder_ == null) {
        result.m_ = m_;
      } else {
        result.m_ = mBuilder_.build();
      }
      if (tBuilder_ == null) {
        result.t_ = t_;
      } else {
        result.t_ = tBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Notification) {
        return mergeFrom((Notification)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Notification other) {
      if (other == Notification.getDefaultInstance()) return this;
      if (!other.getClientName().isEmpty()) {
        clientName_ = other.clientName_;
        onChanged();
      }
      if (!other.getServerName().isEmpty()) {
        serverName_ = other.serverName_;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.hasA()) {
        mergeA(other.getA());
      }
      if (other.hasM()) {
        mergeM(other.getM());
      }
      if (other.hasT()) {
        mergeT(other.getT());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Notification parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Notification) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object clientName_ = "";
    /**
     * <code>string clientName = 1;</code>
     */
    public String getClientName() {
      Object ref = clientName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string clientName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientNameBytes() {
      Object ref = clientName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientName = 1;</code>
     */
    public Builder setClientName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clientName = 1;</code>
     */
    public Builder clearClientName() {
      
      clientName_ = getDefaultInstance().getClientName();
      onChanged();
      return this;
    }
    /**
     * <code>string clientName = 1;</code>
     */
    public Builder setClientNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientName_ = value;
      onChanged();
      return this;
    }

    private Object serverName_ = "";
    /**
     * <code>string serverName = 2;</code>
     */
    public String getServerName() {
      Object ref = serverName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string serverName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      Object ref = serverName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serverName = 2;</code>
     */
    public Builder setServerName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serverName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string serverName = 2;</code>
     */
    public Builder clearServerName() {
      
      serverName_ = getDefaultInstance().getServerName();
      onChanged();
      return this;
    }
    /**
     * <code>string serverName = 2;</code>
     */
    public Builder setServerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serverName_ = value;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.grpc.topicType type = 3;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.grpc.topicType type = 3;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.topicType type = 3;</code>
     */
    public topicType getType() {
      topicType result = topicType.valueOf(type_);
      return result == null ? topicType.UNRECOGNIZED : result;
    }
    /**
     * <code>.grpc.topicType type = 3;</code>
     */
    public Builder setType(topicType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.topicType type = 3;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private Alert a_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Alert, Alert.Builder, com.coalvalue.rpc.grpc.notif.AlertOrBuilder> aBuilder_;
    /**
     * <code>.grpc.Alert a = 6;</code>
     */
    public boolean hasA() {
      return aBuilder_ != null || a_ != null;
    }
    /**
     * <code>.grpc.Alert a = 6;</code>
     */
    public Alert getA() {
      if (aBuilder_ == null) {
        return a_ == null ? Alert.getDefaultInstance() : a_;
      } else {
        return aBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.Alert a = 6;</code>
     */
    public Builder setA(Alert value) {
      if (aBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        a_ = value;
        onChanged();
      } else {
        aBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Alert a = 6;</code>
     */
    public Builder setA(
        Alert.Builder builderForValue) {
      if (aBuilder_ == null) {
        a_ = builderForValue.build();
        onChanged();
      } else {
        aBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.Alert a = 6;</code>
     */
    public Builder mergeA(Alert value) {
      if (aBuilder_ == null) {
        if (a_ != null) {
          a_ =
            Alert.newBuilder(a_).mergeFrom(value).buildPartial();
        } else {
          a_ = value;
        }
        onChanged();
      } else {
        aBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Alert a = 6;</code>
     */
    public Builder clearA() {
      if (aBuilder_ == null) {
        a_ = null;
        onChanged();
      } else {
        a_ = null;
        aBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.Alert a = 6;</code>
     */
    public Alert.Builder getABuilder() {
      
      onChanged();
      return getAFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.Alert a = 6;</code>
     */
    public com.coalvalue.rpc.grpc.notif.AlertOrBuilder getAOrBuilder() {
      if (aBuilder_ != null) {
        return aBuilder_.getMessageOrBuilder();
      } else {
        return a_ == null ?
            Alert.getDefaultInstance() : a_;
      }
    }
    /**
     * <code>.grpc.Alert a = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Alert, Alert.Builder, com.coalvalue.rpc.grpc.notif.AlertOrBuilder>
        getAFieldBuilder() {
      if (aBuilder_ == null) {
        aBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Alert, Alert.Builder, com.coalvalue.rpc.grpc.notif.AlertOrBuilder>(
                getA(),
                getParentForChildren(),
                isClean());
        a_ = null;
      }
      return aBuilder_;
    }

    private Mode m_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Mode, Mode.Builder, com.coalvalue.rpc.grpc.notif.ModeOrBuilder> mBuilder_;
    /**
     * <code>.grpc.Mode m = 4;</code>
     */
    public boolean hasM() {
      return mBuilder_ != null || m_ != null;
    }
    /**
     * <code>.grpc.Mode m = 4;</code>
     */
    public Mode getM() {
      if (mBuilder_ == null) {
        return m_ == null ? Mode.getDefaultInstance() : m_;
      } else {
        return mBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.Mode m = 4;</code>
     */
    public Builder setM(Mode value) {
      if (mBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        m_ = value;
        onChanged();
      } else {
        mBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Mode m = 4;</code>
     */
    public Builder setM(
        Mode.Builder builderForValue) {
      if (mBuilder_ == null) {
        m_ = builderForValue.build();
        onChanged();
      } else {
        mBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.Mode m = 4;</code>
     */
    public Builder mergeM(Mode value) {
      if (mBuilder_ == null) {
        if (m_ != null) {
          m_ =
            Mode.newBuilder(m_).mergeFrom(value).buildPartial();
        } else {
          m_ = value;
        }
        onChanged();
      } else {
        mBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Mode m = 4;</code>
     */
    public Builder clearM() {
      if (mBuilder_ == null) {
        m_ = null;
        onChanged();
      } else {
        m_ = null;
        mBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.Mode m = 4;</code>
     */
    public Mode.Builder getMBuilder() {
      
      onChanged();
      return getMFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.Mode m = 4;</code>
     */
    public com.coalvalue.rpc.grpc.notif.ModeOrBuilder getMOrBuilder() {
      if (mBuilder_ != null) {
        return mBuilder_.getMessageOrBuilder();
      } else {
        return m_ == null ?
            Mode.getDefaultInstance() : m_;
      }
    }
    /**
     * <code>.grpc.Mode m = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Mode, Mode.Builder, com.coalvalue.rpc.grpc.notif.ModeOrBuilder>
        getMFieldBuilder() {
      if (mBuilder_ == null) {
        mBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Mode, Mode.Builder, com.coalvalue.rpc.grpc.notif.ModeOrBuilder>(
                getM(),
                getParentForChildren(),
                isClean());
        m_ = null;
      }
      return mBuilder_;
    }

    private Temp t_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Temp, Temp.Builder, com.coalvalue.rpc.grpc.notif.TempOrBuilder> tBuilder_;
    /**
     * <code>.grpc.Temp t = 5;</code>
     */
    public boolean hasT() {
      return tBuilder_ != null || t_ != null;
    }
    /**
     * <code>.grpc.Temp t = 5;</code>
     */
    public Temp getT() {
      if (tBuilder_ == null) {
        return t_ == null ? Temp.getDefaultInstance() : t_;
      } else {
        return tBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.Temp t = 5;</code>
     */
    public Builder setT(Temp value) {
      if (tBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        t_ = value;
        onChanged();
      } else {
        tBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Temp t = 5;</code>
     */
    public Builder setT(
        Temp.Builder builderForValue) {
      if (tBuilder_ == null) {
        t_ = builderForValue.build();
        onChanged();
      } else {
        tBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.Temp t = 5;</code>
     */
    public Builder mergeT(Temp value) {
      if (tBuilder_ == null) {
        if (t_ != null) {
          t_ =
            Temp.newBuilder(t_).mergeFrom(value).buildPartial();
        } else {
          t_ = value;
        }
        onChanged();
      } else {
        tBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Temp t = 5;</code>
     */
    public Builder clearT() {
      if (tBuilder_ == null) {
        t_ = null;
        onChanged();
      } else {
        t_ = null;
        tBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.Temp t = 5;</code>
     */
    public Temp.Builder getTBuilder() {
      
      onChanged();
      return getTFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.Temp t = 5;</code>
     */
    public com.coalvalue.rpc.grpc.notif.TempOrBuilder getTOrBuilder() {
      if (tBuilder_ != null) {
        return tBuilder_.getMessageOrBuilder();
      } else {
        return t_ == null ?
            Temp.getDefaultInstance() : t_;
      }
    }
    /**
     * <code>.grpc.Temp t = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Temp, Temp.Builder, com.coalvalue.rpc.grpc.notif.TempOrBuilder>
        getTFieldBuilder() {
      if (tBuilder_ == null) {
        tBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Temp, Temp.Builder, com.coalvalue.rpc.grpc.notif.TempOrBuilder>(
                getT(),
                getParentForChildren(),
                isClean());
        t_ = null;
      }
      return tBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.Notification)
  }

  // @@protoc_insertion_point(class_scope:grpc.Notification)
  private static final Notification DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Notification();
  }

  public static Notification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Notification>
      PARSER = new com.google.protobuf.AbstractParser<Notification>() {
    public Notification parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Notification(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Notification> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Notification> getParserForType() {
    return PARSER;
  }

  public Notification getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

