// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pushnotif.proto

package com.coalvalue.rpc.grpc.notif;

public final class Pushnotif {
  private Pushnotif() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_Alert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_Alert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_Mode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_Mode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_Temp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_Temp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_RegistrationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_RegistrationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_RegistrationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_RegistrationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_Topic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_Topic_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_Notification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_Notification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017pushnotif.proto\022\004grpc\"\030\n\005Alert\022\017\n\007mess" +
      "age\030\001 \001(\t\"\027\n\004Mode\022\017\n\007newMode\030\001 \001(\t\"\027\n\004Te" +
      "mp\022\017\n\007newTemp\030\001 \001(\r\")\n\023RegistrationReque" +
      "st\022\022\n\nclientName\030\001 \001(\t\">\n\024RegistrationRe" +
      "sponse\022\022\n\nclientName\030\001 \001(\t\022\022\n\nserverName" +
      "\030\002 \001(\t\":\n\005Topic\022\022\n\nclientName\030\001 \001(\t\022\035\n\004t" +
      "ype\030\002 \001(\0162\017.grpc.topicType\"\233\001\n\014Notificat" +
      "ion\022\022\n\nclientName\030\001 \001(\t\022\022\n\nserverName\030\002 " +
      "\001(\t\022\035\n\004type\030\003 \001(\0162\017.grpc.topicType\022\026\n\001a\030" +
      "\006 \001(\0132\013.grpc.Alert\022\025\n\001m\030\004 \001(\0132\n.grpc.Mod" +
      "e\022\025\n\001t\030\005 \001(\0132\n.grpc.Temp**\n\ttopicType\022\t\n" +
      "\005ALERT\020\000\022\010\n\004MODE\020\001\022\010\n\004TEMP\020\0022\254\001\n\tpushNot" +
      "if\022A\n\010Register\022\031.grpc.RegistrationReques" +
      "t\032\032.grpc.RegistrationResponse\022*\n\005Alert\022\013" +
      ".grpc.Topic\032\022.grpc.Notification0\001\0220\n\tSub" +
      "scribe\022\013.grpc.Topic\032\022.grpc.Notification(" +
      "\0010\001B \n\034com.coalvalue.rpc.grpc.notifP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpc_Alert_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_Alert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_Alert_descriptor,
        new String[] { "Message", });
    internal_static_grpc_Mode_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_Mode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_Mode_descriptor,
        new String[] { "NewMode", });
    internal_static_grpc_Temp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_Temp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_Temp_descriptor,
        new String[] { "NewTemp", });
    internal_static_grpc_RegistrationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpc_RegistrationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_RegistrationRequest_descriptor,
        new String[] { "ClientName", });
    internal_static_grpc_RegistrationResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_grpc_RegistrationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_RegistrationResponse_descriptor,
        new String[] { "ClientName", "ServerName", });
    internal_static_grpc_Topic_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_grpc_Topic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_Topic_descriptor,
        new String[] { "ClientName", "Type", });
    internal_static_grpc_Notification_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_grpc_Notification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_Notification_descriptor,
        new String[] { "ClientName", "ServerName", "Type", "A", "M", "T", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
