// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pushnotif.proto

package com.coalvalue.rpc.grpc.notif;

public interface RegistrationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.RegistrationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientName = 1;</code>
   */
  String getClientName();
  /**
   * <code>string clientName = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <pre>
   * uint64 clientCookie = 3; Cookie assigned by the server which is used in further communications 
   * </pre>
   *
   * <code>string serverName = 2;</code>
   */
  String getServerName();
  /**
   * <pre>
   * uint64 clientCookie = 3; Cookie assigned by the server which is used in further communications 
   * </pre>
   *
   * <code>string serverName = 2;</code>
   */
  com.google.protobuf.ByteString
      getServerNameBytes();
}
