// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pushnotif.proto

package com.coalvalue.rpc.grpc.notif;

public interface RegistrationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.RegistrationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientName = 1;</code>
   */
  String getClientName();
  /**
   * <code>string clientName = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientNameBytes();
}
