// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pushnotif.proto

package com.coalvalue.rpc.grpc.notif;

/**
 * Protobuf enum {@code grpc.topicType}
 */
public enum topicType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ALERT = 0;</code>
   */
  ALERT(0),
  /**
   * <code>MODE = 1;</code>
   */
  MODE(1),
  /**
   * <code>TEMP = 2;</code>
   */
  TEMP(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ALERT = 0;</code>
   */
  public static final int ALERT_VALUE = 0;
  /**
   * <code>MODE = 1;</code>
   */
  public static final int MODE_VALUE = 1;
  /**
   * <code>TEMP = 2;</code>
   */
  public static final int TEMP_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static topicType valueOf(int value) {
    return forNumber(value);
  }

  public static topicType forNumber(int value) {
    switch (value) {
      case 0: return ALERT;
      case 1: return MODE;
      case 2: return TEMP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<topicType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      topicType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<topicType>() {
          public topicType findValueByNumber(int number) {
            return topicType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return Pushnotif.getDescriptor().getEnumTypes().get(0);
  }

  private static final topicType[] VALUES = values();

  public static topicType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private topicType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:grpc.topicType)
}

