// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pushnotif.proto

package com.coalvalue.rpc.grpc.notif;

public interface TopicOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Topic)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientName = 1;</code>
   */
  String getClientName();
  /**
   * <code>string clientName = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <pre>
   * uint64 clientCookie = 1; 
   * </pre>
   *
   * <code>.grpc.topicType type = 2;</code>
   */
  int getTypeValue();
  /**
   * <pre>
   * uint64 clientCookie = 1; 
   * </pre>
   *
   * <code>.grpc.topicType type = 2;</code>
   */
  topicType getType();
}
