// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pushnotif.proto

package com.coalvalue.python.server;

/**
 * Protobuf enum {@code grpc.topicType}
 */
public enum ServerType {
  /**
   * <code>ALERT = 0;</code>
   */
  JAVA(0),
  /**
   * <code>MODE = 1;</code>
   */
  MODE(1),
  /**
   * <code>TEMP = 2;</code>
   */
  TEMP(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ALERT = 0;</code>
   */
  public static final int ALERT_VALUE = 0;
  /**
   * <code>MODE = 1;</code>
   */
  public static final int MODE_VALUE = 1;
  /**
   * <code>TEMP = 2;</code>
   */
  public static final int TEMP_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static ServerType valueOf(int value) {
    return forNumber(value);
  }

  public static ServerType forNumber(int value) {
    switch (value) {
      case 0: return JAVA;
      case 1: return MODE;
      case 2: return TEMP;
      default: return null;
    }
  }


  private final int value;

  private ServerType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:grpc.topicType)
}

